print("Введите слово:")
str = input()
print("Ваше слово: " + str)
str_uppercase = str.upper()
print("Ваше слово в верхнем регистре: " + str_uppercase)
num_half = int(len(str_uppercase) / 2)
print("Половинка Вашего слова в верхнем регистре: " + str_uppercase[:num_half])
